language: haxe

haxe:
  - 3.4.7
  - development

install:
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
  - haxelib install vscode
  - haxelib install vshaxe
  - haxelib install json2object
  - haxelib install munit
  - haxelib git hamcrest https://github.com/kaikoga/hamcrest-haxe patch-haxe4-p5 src
  - haxelib install utest
  - haxelib install hx3compat
  - haxelib install buddy
  - haxelib install hexunit
  - haxelib dev test-adapter test-adapter

script:
  - haxe --run RunCI
