language: haxe

haxe:
  - development

install:
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
  - haxelib install vscode
  - haxelib install vshaxe
  - haxelib install json2object
  - haxelib install munit
  - haxelib git hamcrest https://github.com/kaikoga/hamcrest-haxe patch-haxe4-p5 src
  - haxelib install utest
  - haxelib install hx3compat
  - haxelib dev test-adapter test-adapter

script:
  - haxe build.hxml
  - cd samples/munit
  - sed -i /--interp/d test.hxml && haxe test.hxml
  - cd ../utest
  - sed -i /--interp/d test.hxml && haxe test.hxml
  - cd ../haxeunit
  - sed -i /--interp/d test.hxml && haxe test.hxml
